import { Clock3, MapPin, Phone, ShieldAlert, Siren, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { Person } from '../../types'

export function EmergencyTestModal({ person, onDetails }: { person: Person; onDetails: () => void }) {
  const [open, setOpen] = useState(false)
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => event.key === 'Escape' && setOpen(false); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [open])
  return <>
    <button onClick={() => setOpen(true)} className="focus-ring inline-flex items-center justify-center gap-2 rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-extrabold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-rose-700 hover:shadow-lg active:translate-y-0"><Siren size={17} />긴급 알림 테스트</button>
    {open && <div className="fixed inset-0 z-[3000] flex items-start justify-center overflow-y-auto bg-slate-950/75 p-4 pt-[max(24px,7vh)] backdrop-blur-sm" role="dialog" aria-modal="true"><button aria-label="모달 닫기" className="absolute inset-0 cursor-default" onClick={() => setOpen(false)} /><section className="emergency-modal relative w-full max-w-lg overflow-hidden rounded-3xl border-2 border-rose-500 bg-white shadow-2xl"><div className="relative overflow-hidden bg-rose-600 px-5 py-6 text-white sm:px-7"><div className="absolute right-3 top-2 opacity-10"><Siren size={120} /></div><button onClick={() => setOpen(false)} aria-label="닫기" className="absolute right-4 top-4 rounded-full bg-white/15 p-2 transition hover:bg-white/25"><X size={19} /></button><div className="flex items-center gap-4"><span className="relative grid h-14 w-14 shrink-0 place-items-center rounded-full bg-white text-rose-600"><ShieldAlert size={29} /><i className="absolute inset-0 animate-ping rounded-full border-2 border-white" /></span><div><p className="text-xs font-extrabold tracking-[.18em] text-rose-100">EMERGENCY SIGNAL</p><h2 className="mt-1 text-xl font-black sm:text-2xl">긴급 안전 확인이 필요해요</h2></div></div></div><div className="p-5 sm:p-7"><div className="rounded-2xl border border-rose-300 bg-rose-100 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-rose-600">긴급 대상자</p><h3 className="mt-1 text-xl font-black text-rose-950">{person.name} <span className="text-sm font-bold text-rose-700">{person.age}세</span></h3></div><span className="rounded-full bg-rose-600 px-3 py-1.5 text-xs font-black text-white">14시간 미활동</span></div><p className="mt-3 text-sm font-semibold leading-6 text-rose-900">{person.reason}</p></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div className="flex gap-3 rounded-xl bg-slate-50 p-3"><MapPin className="shrink-0 text-slate-400" size={18} /><div><p className="text-xs text-slate-400">거주 위치</p><b>{person.address}</b></div></div><div className="flex gap-3 rounded-xl bg-slate-50 p-3"><Clock3 className="shrink-0 text-slate-400" size={18} /><div><p className="text-xs text-slate-400">마지막 연락</p><b>{person.lastContactAt}</b></div></div></div><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row"><button onClick={() => setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-600 transition hover:bg-slate-50 sm:flex-1">나중에 확인</button><button onClick={() => { setOpen(false); onDetails() }} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white transition hover:bg-slate-800 sm:flex-1">상세 확인</button><a href={`tel:${person.phone}`} className="flex items-center justify-center gap-2 rounded-xl bg-rose-600 px-4 py-3 text-sm font-extrabold text-white transition hover:bg-rose-700 sm:flex-1"><Phone size={16} />즉시 전화</a></div></div></section></div>}
  </>
}
