import { Activity, ArrowRight, Radio, TrendingDown } from 'lucide-react'
import { people } from '../../data/mockData'
import { useLiveMeasurements } from '../../hooks/useLiveMeasurements'
import type { Page, Person } from '../../types'
import { RiskBadge } from '../ui/RiskBadge'

export function PowerSummaryCard({resolvedPersonIds,onSelect,setPage}:{resolvedPersonIds:Set<number>;onSelect:(person:Person)=>void;setPage:(page:Page)=>void}){
  const{measurements,lastUpdated}=useLiveMeasurements()
  const signals=people.filter(person=>person.risk!=='정상'&&!resolvedPersonIds.has(person.id)).map(person=>({person,measurement:measurements.find(item=>item.personId===person.id)!})).sort((a,b)=>Math.abs(b.measurement.deviationPercent)-Math.abs(a.measurement.deviationPercent))
  const averageDeviation=signals.length?signals.reduce((sum,item)=>sum+Math.abs(item.measurement.deviationPercent),0)/signals.length:0
  const time=lastUpdated.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})
  return <section className="card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-700"><Radio size={18}/></span><div><h3 className="font-extrabold">전력 모니터링 요약</h3><p className="mt-0.5 text-xs text-slate-500">현재 감지된 생활 전력 이상 신호</p></div></div><button onClick={()=>setPage('power')} className="group flex items-center gap-1 rounded-lg px-2 py-1 text-xs font-bold text-brand-700 hover:bg-brand-50">전체 보기<ArrowRight size={14} className="transition group-hover:translate-x-1"/></button></header><div className="grid grid-cols-3 divide-x divide-slate-100 border-b border-slate-100"><div className="p-4"><p className="text-[11px] font-semibold text-slate-400">이상 신호</p><p className="mt-1 text-xl font-black text-rose-600">{signals.length}<span className="ml-1 text-xs text-slate-400">명</span></p></div><div className="p-4"><p className="text-[11px] font-semibold text-slate-400">평균 편차</p><p className="mt-1 text-xl font-black">-{averageDeviation.toFixed(1)}<span className="ml-1 text-xs text-slate-400">%</span></p></div><div className="p-4"><p className="text-[11px] font-semibold text-slate-400">최근 수신</p><p className="mt-1 text-sm font-black text-emerald-700">LIVE</p><p className="text-[10px] text-slate-400">{time}</p></div></div><div className="divide-y divide-slate-100 px-3">{signals.slice(0,3).map(({person,measurement})=><button key={person.id} onClick={()=>onSelect(person)} className="group flex w-full items-center gap-3 rounded-lg px-2 py-3 text-left transition hover:bg-slate-50"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-extrabold">{person.name.slice(-2)}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="text-sm group-hover:text-brand-700">{person.name}</b><RiskBadge risk={person.risk}/></div><p className="mt-1 truncate text-[11px] text-slate-500">{measurement.reason}</p></div><div className="shrink-0 text-right"><b className="text-sm tabular-nums">{measurement.watts.toFixed(1)}W</b><p className="mt-1 flex items-center justify-end text-[11px] font-bold text-rose-600"><TrendingDown size={12}/>{measurement.deviationPercent.toFixed(1)}%</p></div></button>)}</div><button onClick={()=>setPage('power')} className="flex w-full items-center justify-center gap-2 border-t border-slate-100 bg-slate-50 px-4 py-3 text-xs font-bold text-slate-600 transition hover:bg-brand-50 hover:text-brand-700"><Activity size={14}/>상세 전력 패턴 확인하기</button></section>
}
